id: AIT117
title: NHP Basal Ganglia taxonomy (Macaque)
description: Atlas of Macaque basal ganglia, developed in collaboration with the BRAIN Initiative Cell Census Network (BICCN).
matrix_file_id: CellXGene_dataset:nhp50930-982a-11ee-b9d1-0242ac120002
github_org: Cellular-Semantics
repo: nhp_basal_ganglia_macaque_taxonomy
author: https://orcid.org/0000-0002-4436-969X
accession_id_prefix: AIT117
citation: ''
creators:
  - https://orcid.org/0000-0002-4436-969X